services:
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: nextdb
      MYSQL_USER: nextuser
      MYSQL_PASSWORD: nextpass
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      

  nextapp:
    build: 
      context: ./next-app
      dockerfile: Dockerfile
    develop:
      watch: 
        - action: sync
          path: ./next-app/app
          target: /app/app
          ignore:
            - node_modules/
        - action: rebuild
          path: ./next-app/package.json
    ports:
      - "3303:3000"  
    depends_on:
      - db
      - flaskapp


  flaskapp:
    build:
      context: ./flask-app  
      dockerfile: Dockerfile
    expose:
      - "5000" 
    environment:
      MYSQL_DB: nextdb
      MYSQL_USER: nextuser
      MYSQL_PASSWORD: nextpass
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      FLAG: RECURSION{banyak_pemanisnya_kayak_palubutung_tapi_gampang_kan}
    depends_on:
      - db

volumes:
  db_data:
