version: '3'
services:
  web:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - FLAG=${FLAG}
    env_file:
      - .env

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: Pablu
      POSTGRES_PASSWORD: pablu09
      POSTGRES_DB: pg-challenge
    ports:
      - "5432:5432"
